const fmt=(n,d=1)=>Number.isFinite(n)?n.toFixed(d):'—';
const satVaporPressure=t=>6.112*Math.exp((17.67*t)/(t+243.5));
function airDensity(t,p,rh){const T=t+273.15,e=satVaporPressure(t)*(rh/100);return ((p-e)*100)/(287.05*T)+(e*100)/(461.495*T)}
function densityAltitude(rho){return (288.15/.0065)*(1-Math.pow(rho/1.225,1/4.25588))}
function fillSelect(id,vals,sel){const s=$(id);s.innerHTML='';vals.forEach(v=>{const o=document.createElement('option');o.value=o.textContent=String(v);s.appendChild(o)});if(vals.map(String).includes(String(sel)))s.value=String(sel)}
const needleList=()=>[...K_VARIANTS];
const getNeedleNotches=c=>NEEDLE_NOTCHES[c]||5;
function updateClipLimits(prefix){const code=val(prefix+'Needle'),max=getNeedleNotches(code),el=$(prefix+'Clip');el.min='1';el.max=String(max);el.step='.5';let v=parseFloat(el.value);if(v>max)el.value=max;if(v<1)el.value=1;const l=$(prefix+'ClipLabel');if(l)l.textContent=`${prefix==='b'?'Tacca':'Tacca test'} · ${max} tacche fisiche · step 0,5`;return max}
function loadNeedleGeometry(prefix){const code=val(prefix+'Needle'),d=NEEDLES[code]||[],max=updateClipLimits(prefix);['A','B','C'].forEach((x,i)=>$(prefix+x).value=d[i]??'');const info=$(prefix+'NeedleInfo');if(info)info.textContent=d[0]==null?`${code}: T ${max} tacche · geometria n/d.`:`${code}: T ${max} tacche · A ${d[0]} mm · B ${d[1]} mm · C ${d[2]} mm`}
function initComponentDB(){fillSelect('bMain',MAIN_JETS,180);fillSelect('tMain',MAIN_JETS,180);fillSelect('bNeedle',needleList(),'K98');fillSelect('tNeedle',needleList(),'K100');fillSelect('bAtom',ATOMIZERS,'DP268');fillSelect('tAtom',ATOMIZERS,'DP268');fillSelect('bIdle',IDLE_KZ,60);fillSelect('tIdle',IDLE_KZ,60);fillSelect('bIdleB',IDLE_B,48);fillSelect('tIdleB',IDLE_B,48);fillSelect('bSlide',SLIDES,50);fillSelect('tSlide',SLIDES,50);loadNeedleGeometry('b');loadNeedleGeometry('t')}
function atomizerParts(c){const m=String(c).match(/^([A-Z]+)(\d+)$/);return m?{type:m[1],size:+m[2]}:{type:'',size:NaN}}
async function searchPlace(){const q=val('place');if(!q){$('weatherMsg').textContent='Inserisci una località.';return}try{const r=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(q)}&count=1&language=it&format=json`),j=await r.json();if(!j.results?.length)throw Error('Località non trovata');const p=j.results[0];await loadWeather(p.latitude,p.longitude,`${p.name}${p.admin1?', '+p.admin1:''}`)}catch(e){$('weatherMsg').textContent='Errore: '+e.message}}
function geoWeather(){if(!navigator.geolocation){$('weatherMsg').textContent='GPS non disponibile.';return}navigator.geolocation.getCurrentPosition(p=>loadWeather(p.coords.latitude,p.coords.longitude,'Posizione GPS'),()=>{$('weatherMsg').textContent='GPS non disponibile/consentito.'})}
async function loadWeather(lat,lon,label){try{$('weatherMsg').textContent='Caricamento meteo...';const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m,surface_pressure&timezone=auto`),j=await r.json(),c=j.current;if(!c)throw Error('Dati non disponibili');const rho=airDensity(c.temperature_2m,c.surface_pressure,c.relative_humidity_2m);weather={label,temp:c.temperature_2m,rh:c.relative_humidity_2m,press:c.surface_pressure,rho,da:densityAltitude(rho),time:c.time};$('wTemp').textContent=fmt(weather.temp);$('wRh').textContent=fmt(weather.rh,0);$('wPress').textContent=fmt(weather.press,0);$('wRho').textContent=fmt(weather.rho,3);$('wDA').textContent=fmt(weather.da,0);$('weatherMsg').textContent=`${label} · ${c.time}`;$('logPlace').value=label;calcCorrection();updateMobileHero()}catch(e){$('weatherMsg').textContent='Errore meteo: '+e.message}}
const baselineDensity=()=>airDensity(num('bTemp'),num('bPress'),num('bRh'));
const nearestNumeric=(a,t)=>a.map(Number).filter(Number.isFinite).reduce((b,v)=>Math.abs(v-t)<Math.abs(b-t)?v:b);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function atomizerCodeSameFamily(code,delta){const p=atomizerParts(code),c=ATOMIZERS.map(atomizerParts).filter(x=>x.type===p.type).map(x=>x.size);return p.type?`${p.type}${nearestNumeric(c,p.size+delta)}`:code}
let suggestedSetup=null;
function calculateSuggestedSetup(){if(!weather){suggestedSetup=null;['sMain','sNeedle','sClip','sAtom','sIdle','sIdleB','sAir','sSlide'].forEach(id=>{if($(id))$(id).textContent='—'});updateMobileHero();return}const ratio=weather.rho/baselineDensity(),pct=(ratio-1)*100,bm=num('bMain'),bi=num('bIdle'),bb=num('bIdleB'),bc=num('bClip'),ba=num('bAir'),bn=val('bNeedle'),bat=val('bAtom');const main=nearestNumeric(MAIN_JETS,bm*ratio),idle=nearestNumeric(IDLE_KZ,bi*Math.sqrt(ratio)),idleB=nearestNumeric(IDLE_B,bb*Math.sqrt(ratio));let cd=0;if(Math.abs(pct)>=2.5)cd=.5*Math.sign(pct);if(Math.abs(pct)>=5)cd=1*Math.sign(pct);if(Math.abs(pct)>=8)cd=1.5*Math.sign(pct);const clip=Math.round(clamp(bc+cd,1,getNeedleNotches(bn))*2)/2;let ad=0;if(Math.abs(pct)>=2)ad=Math.sign(pct);if(Math.abs(pct)>=6)ad=2*Math.sign(pct);const atom=atomizerCodeSameFamily(bat,ad);let air=ba;if(Math.abs(pct)>=2)air=ba-.25*Math.sign(pct);if(Math.abs(pct)>=5.5)air=ba-.5*Math.sign(pct);air=Math.round(clamp(air,.5,3)*4)/4;suggestedSetup={main,needle:bn,clip,atom,idle,idleB,air,slide:val('bSlide'),pct};$('sMain').textContent=main;$('sNeedle').textContent=bn;$('sClip').textContent=clip;$('sAtom').textContent=atom;$('sIdle').textContent=idle;$('sIdleB').textContent='B'+idleB;$('sAir').textContent=air.toFixed(2);$('sSlide').textContent=suggestedSetup.slide;$('sMainDelta').textContent=`${main-bm>0?'+':''}${main-bm} vs baseline`;$('sClipDelta').textContent=`${clip-bc>0?'+':''}${clip-bc} vs baseline · max ${getNeedleNotches(bn)}`;$('suggestedWeather').innerHTML=`<b>${weather.label}</b> · ${weather.temp.toFixed(1)} °C · ${Math.round(weather.press)} hPa · ${Math.round(weather.rh)}% RH · aria ${pct<0?'meno':'più'} densa (${pct>=0?'+':''}${pct.toFixed(1)}%)`;const changes=[];if(main!==bm)changes.push(`max ${bm}→${main}`);if(atom!==bat)changes.push(`${bat}→${atom}`);if(clip!==bc)changes.push(`tacca ${bc}→${clip}`);$('suggestedReason').textContent=changes.length?`Correzioni suggerite: ${changes.join(' · ')}.`:'Condizioni vicine alla baseline: mantieni il setup.';updateMobileHero()}
function calcCorrection(){$('mainBaseView').textContent=val('bMain')||'—';if(!weather){calculateSuggestedSetup();return}const ratio=weather.rho/baselineDensity(),pct=(ratio-1)*100;$('densityDelta').textContent=(pct>=0?'+':'')+pct.toFixed(1)+'%';const s=$('densityStatus');if(pct>.8){s.textContent='ARIA PIÙ DENSA';s.className='status lean';$('densityText').textContent='Tende a smagrire'}else if(pct<-.8){s.textContent='ARIA MENO DENSA';s.className='status rich';$('densityText').textContent='Tende a ingrassire'}else{s.textContent='QUASI UGUALE';s.className='status neutral';$('densityText').textContent='Correzione minima'}const target=num('bMain')*Math.sqrt(ratio);$('mainSuggestion').textContent=Math.round(target);$('recommendation').textContent=`Equivalente teorico circa ${Math.round(target)}. Il profilo KZ Race sotto usa una correzione più aggressiva.`;calculateSuggestedSetup()}
function setBaselineFromWeather(){if(!weather)return alert('Carica prima il meteo.');$('bTemp').value=weather.temp.toFixed(1);$('bPress').value=weather.press.toFixed(1);$('bRh').value=Math.round(weather.rh);saveBaseline()}
function baselineObj(){return ['bTemp','bPress','bRh','bMain','bNeedle','bClip','bAtom','bIdle','bIdleB','bAir','bSlide'].reduce((o,k)=>(o[k]=$(k).value,o),{})}
function saveBaseline(){localStorage.setItem('cw_baseline',JSON.stringify(baselineObj()));calcCorrection()}
function loadBaseline(){try{const o=JSON.parse(localStorage.getItem('cw_baseline')||'{}');Object.entries(o).forEach(([k,v])=>{if($(k))$(k).value=v})}catch{}}
function copyBaselineToTest(){({bMain:'tMain',bNeedle:'tNeedle',bClip:'tClip',bAtom:'tAtom',bIdle:'tIdle',bIdleB:'tIdleB',bAir:'tAir',bSlide:'tSlide'});[['bMain','tMain'],['bNeedle','tNeedle'],['bClip','tClip'],['bAtom','tAtom'],['bIdle','tIdle'],['bIdleB','tIdleB'],['bAir','tAir'],['bSlide','tSlide']].forEach(([a,b])=>$(b).value=$(a).value);loadNeedleGeometry('t');compareSetup()}
function compareSetup(){const bm=num('bMain'),tm=num('tMain'),bc=num('bClip'),tc=num('tClip'),bi=num('bIdle'),ti=num('tIdle'),ba=num('bAir'),ta=num('tAir');let z=[0,0,0,0,0];const ip=bi?((ti-bi)/bi)*100:0;z[0]+=ip*.8;z[1]+=ip*.25;const mp=bm?((tm-bm)/bm)*100:0;z[2]+=mp*.15;z[3]+=mp*.45;z[4]+=mp;const cd=tc-bc;z[1]+=cd*2.2;z[2]+=cd*5;z[3]+=cd*4;z[4]+=cd*1.2;z[0]-=(ta-ba)*3;z[1]-=(ta-ba)*.8;const B=atomizerParts(val('bAtom')),T=atomizerParts(val('tAtom'));if(Number.isFinite(B.size)&&Number.isFinite(T.size)){const d=T.size-B.size;z[1]+=d*.65;z[2]+=d*1.25;z[3]+=d*1.05;z[4]+=d*.25;const f={DQ:0,DP:1},df=(f[T.type]??0)-(f[B.type]??0);z[1]+=df*1.4;z[2]+=df*3.6;z[3]+=df*3;z[4]+=df*.9}const bA=num('bA'),tA=num('tA'),bB=num('bB'),tB=num('tB');if(Number.isFinite(bA)&&Number.isFinite(tA)){z[1]+=(bA-tA)*70;z[2]+=(bA-tA)*45}if(Number.isFinite(bB)&&Number.isFinite(tB)){z[2]+=(bB-tB)*15;z[3]+=(bB-tB)*45;z[4]+=(bB-tB)*25}if($('atomizerComparison'))$('atomizerComparison').textContent=val('bAtom')===val('tAtom')?'Confronto polverizzatore: nessuna variazione.':`${val('bAtom')} → ${val('tAtom')}: ${T.type==='DQ'&&B.type==='DP'?'tendenza più magra':'variazione combinata numero/famiglia'}.`;document.querySelectorAll('#zones .zone').forEach((el,i)=>{const sc=clamp(z[i],-15,15),bar=el.querySelector('i'),out=el.querySelector('.zoneVal');bar.className=sc<0?'neg':'';bar.style.width=(Math.abs(sc)/15*50)+'%';out.textContent=Math.abs(sc)<.6?'≈ uguale':(sc>0?'più ricco ':'più magro ')+Math.abs(sc).toFixed(1)})}
function applySuggestedSetup(){if(!suggestedSetup)return alert('Carica prima il meteo.');[['tMain','main'],['tNeedle','needle'],['tClip','clip'],['tAtom','atom'],['tIdle','idle'],['tIdleB','idleB'],['tAir','air'],['tSlide','slide']].forEach(([id,k])=>$(id).value=String(suggestedSetup[k]));loadNeedleGeometry('t');compareSetup()}
function updateMobileHero(){if($('mTrack')){$('mTrack').textContent=weather?.label||val('logPlace')||'Pista non selezionata';$('mWeather').textContent=weather?`${weather.temp.toFixed(1)} °C · ${Math.round(weather.press)} hPa · ${Math.round(weather.rh)}% RH`:'Carica il meteo per iniziare'}$('mMain').textContent=suggestedSetup?.main??'—';$('mAtom').textContent=suggestedSetup?.atom??'—';$('mNeedle').textContent=suggestedSetup?`${suggestedSetup.needle} T${suggestedSetup.clip}`:'—';const b=window.telemetryData?.best;$('mEgtMin').textContent=b&&Number.isFinite(b.validMin)?Math.round(b.validMin):'—';$('mEgtMax').textContent=b&&Number.isFinite(b.max)?Math.round(b.max):'—'}