const CLOUD_URL='https://izcubkmwgcbalrqqymlv.supabase.co';
const CLOUD_KEY='sb_publishable_RviwW29xv4WHoTCvcY_U6A_4wiaCZ_6';
let cloud=null, cloudUser=null;
function cloudStatus(text,cls=''){const el=document.getElementById('cloudStatus');if(el){el.textContent=text;el.className='cloudStatus '+cls}}
function cloudPanel(){const h=document.querySelector('header');if(!h||document.getElementById('cloudBox'))return;const box=document.createElement('div');box.id='cloudBox';box.className='cloudBox';box.innerHTML=`<button id="cloudBtn" class="cloudChip" type="button">☁ <span id="cloudStatus">Cloud offline</span></button><div id="cloudMenu" class="cloudMenu"><div class="cloudTitle">KZ CLOUD</div><input id="cloudEmail" type="email" placeholder="Email"><input id="cloudPassword" type="password" placeholder="Password"><div class="cloudActions"><button class="btn" id="cloudLogin">Login</button><button class="btn2" id="cloudSignup">Crea account</button></div><div class="cloudActions"><button class="btn2" id="cloudSync">Sync ora</button><button class="btnDanger" id="cloudLogout">Logout</button></div><div class="note" id="cloudMsg">Login per sincronizzare PC e smartphone.</div></div>`;h.appendChild(box);document.getElementById('cloudBtn').onclick=()=>document.getElementById('cloudMenu').classList.toggle('open');document.getElementById('cloudLogin').onclick=cloudLogin;document.getElementById('cloudSignup').onclick=cloudSignup;document.getElementById('cloudLogout').onclick=cloudLogout;document.getElementById('cloudSync').onclick=syncAllCloud}
function cloudMsg(t){const e=document.getElementById('cloudMsg');if(e)e.textContent=t}
async function initCloud(){cloudPanel();if(!window.supabase){cloudStatus('Cloud non disponibile','bad');return}cloud=window.supabase.createClient(CLOUD_URL,CLOUD_KEY,{auth:{persistSession:true,autoRefreshToken:true}});const {data:{session}}=await cloud.auth.getSession();cloudUser=session?.user||null;updateCloudUI();cloud.auth.onAuthStateChange((_e,s)=>{cloudUser=s?.user||null;updateCloudUI();if(cloudUser)syncAllCloud()});wrapCloudHooks()}
function updateCloudUI(){if(cloudUser){cloudStatus('Cloud sync','good');cloudMsg(cloudUser.email||'Connesso')}else{cloudStatus('Cloud offline','');cloudMsg('Login per sincronizzare PC e smartphone.')}['cloudSync','cloudLogout'].forEach(id=>{const e=document.getElementById(id);if(e)e.style.display=cloudUser?'inline-block':'none'})}
async function cloudLogin(){const email=document.getElementById('cloudEmail').value.trim(),password=document.getElementById('cloudPassword').value;if(!email||!password)return cloudMsg('Inserisci email e password.');cloudMsg('Login...');const {error}=await cloud.auth.signInWithPassword({email,password});cloudMsg(error?error.message:'Connesso. Sincronizzazione in corso...')}
async function cloudSignup(){const email=document.getElementById('cloudEmail').value.trim(),password=document.getElementById('cloudPassword').value;if(!email||password.length<6)return cloudMsg('Email valida e password di almeno 6 caratteri.');cloudMsg('Creazione account...');const {data,error}=await cloud.auth.signUp({email,password});if(error)return cloudMsg(error.message);cloudMsg(data.session?'Account creato e connesso.':'Account creato. Controlla la mail di conferma, poi fai login.')}
async function cloudLogout(){await cloud.auth.signOut();cloudUser=null;updateCloudUI()}
async function saveBaselineCloud(){if(!cloudUser)return;const data=baselineObj();await cloud.from('baselines').upsert({user_id:cloudUser.id,name:'Default',data},{onConflict:'user_id,name'})}
async function pullBaselineCloud(){if(!cloudUser)return;const {data}=await cloud.from('baselines').select('data').eq('user_id',cloudUser.id).eq('name','Default').maybeSingle();if(data?.data){Object.entries(data.data).forEach(([k,v])=>{if(document.getElementById(k))document.getElementById(k).value=v});localStorage.setItem('cw_baseline',JSON.stringify(data.data));loadNeedleGeometry('b');calcCorrection()}}
async function syncLogsCloud(){if(!cloudUser)return;let logs=JSON.parse(localStorage.getItem('cw_logs')||'[]');let changed=false;for(const x of logs){if(!x._cloud_id){x._cloud_id=crypto.randomUUID();changed=true}await cloud.from('track_logs').upsert({user_id:cloudUser.id,client_key:x._cloud_id,event_date:x.date||null,place:x.place||null,data:x,notes:x.notes||null},{onConflict:'user_id,client_key'})}if(changed)localStorage.setItem('cw_logs',JSON.stringify(logs));const {data}=await cloud.from('track_logs').select('client_key,data').eq('user_id',cloudUser.id).order('created_at',{ascending:true});if(data){const map=new Map(logs.map(x=>[x._cloud_id,x]));data.forEach(r=>{const x=r.data||{};x._cloud_id=r.client_key;map.set(r.client_key,x)});logs=[...map.values()];localStorage.setItem('cw_logs',JSON.stringify(logs));renderLogs()}}
async function saveTelemetryCloud(){if(!cloudUser||!window.telemetryData||telemetryData.type!=='alfano7')return;const t=telemetryData,key=t.filename||crypto.randomUUID();const summary={best:t.best?{lap:t.best.lap,time:t.best.time,min:t.best.min,validMin:t.best.validMin,max:t.best.max}:null,low:t.low,high:t.high,stats:t.stats};const {data:s,error}=await cloud.from('alfano_sessions').upsert({user_id:cloudUser.id,client_key:key,session_name:key,source_file:key,summary},{onConflict:'user_id,client_key'}).select('id').single();if(error||!s)return;const laps=(t.lapStats||[]).map(x=>({session_id:s.id,user_id:cloudUser.id,lap_no:x.lap,lap_time_ms:Number.isFinite(x.time)?Math.round(x.time):null,egt_min_raw:x.min,egt_min_valid:x.validMin,egt_max:x.max,water_min:x.waterMin,water_max:x.waterMax,rpm_max:x.rpmMax,speed_max:x.speedMax,above_target_pct:x.above}));if(laps.length)await cloud.from('alfano_laps').upsert(laps,{onConflict:'session_id,lap_no'})}
async function syncAllCloud(){if(!cloudUser)return cloudMsg('Fai login prima.');cloudStatus('Sync...');try{await saveBaselineCloud();await pullBaselineCloud();await syncLogsCloud();await saveTelemetryCloud();cloudStatus('Cloud sync','good');cloudMsg('Sincronizzazione completata.')}catch(e){cloudStatus('Sync error','bad');cloudMsg(e.message||'Errore sync')}}
function wrapCloudHooks(){if(typeof saveBaseline==='function'&&!saveBaseline._cloudWrapped){const o=saveBaseline;window.saveBaseline=function(){const r=o.apply(this,arguments);saveBaselineCloud();return r};window.saveBaseline._cloudWrapped=true}if(typeof addLog==='function'&&!addLog._cloudWrapped){const o=addLog;window.addLog=function(){const r=o.apply(this,arguments);syncLogsCloud();return r};window.addLog._cloudWrapped=true}if(typeof importAlfanoZip==='function'&&!importAlfanoZip._cloudWrapped){const o=importAlfanoZip;window.importAlfanoZip=async function(){const r=await o.apply(this,arguments);await saveTelemetryCloud();return r};window.importAlfanoZip._cloudWrapped=true}}
setTimeout(initCloud,0);